[package]
name = "tpt-concord-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "TPT Concord: cli crate (see spec.txt)"

[dependencies]
tpt-concord-core = { workspace = true }
