// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright 2026 TPT Solutions

//! `tpt-concord-fuzz` — specification-driven fuzzing (spec §5).
//!
//! - **state-transition-aware**: sequences are generated by walking a
//!   reference model (via `tpt-concord-property::stateful_sequence`), so the
//!   fuzzer spends its budget on inputs the specification says are reachable;
//! - **invariant checks**: the caller supplies the check executed over every
//!   generated sequence (typically: run the implementation, verify
//!   invariants/`conformance` after each step);
//! - **corpus management**: a directory-backed corpus of interesting inputs,
//!   content-addressed and used to seed campaigns;
//! - **reproducible failures**: every failure is minimized (shrunk), stored
//!   as JSON with its seed, and re-runnable bit-for-bit.

pub mod corpus;

pub use corpus::Corpus;

use serde::Serialize;
use serde_json::Value as Json;
use sha2::{Digest, Sha256};
use std::path::Path;
use tpt_concord_model::AbstractModel;
use tpt_concord_property::rng::Rng;
use tpt_concord_property::shrink;
use tpt_concord_property::strategy::stateful_sequence;

/// One minimized, reproducible failure.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct MinimizedFailure<I> {
    /// Seed that generated the original (pre-shrink) sequence.
    pub seed: u64,
    /// Minimal failing sequence.
    pub input: Vec<I>,
    /// The check's failure reason.
    pub reason: String,
}

/// Outcome of a fuzz campaign.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuzzReport<I> {
    pub cycles: usize,
    /// Failures found and minimized (empty when the campaign is clean).
    pub failures: Vec<MinimizedFailure<I>>,
}

impl<I> FuzzReport<I> {
    /// True iff no failures were found. Note: a clean campaign is
    /// `fuzz_tested` evidence, never proof.
    pub fn is_clean(&self) -> bool {
        self.failures.is_empty()
    }
}

/// Content hash (SHA-256 hex) of a serialized input.
pub fn input_digest(input: &Json) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.to_string().as_bytes());
    hex::encode(hasher.finalize())
}

/// Serialize an input sequence to JSON.
pub fn sequence_to_json<I: Serialize>(seq: &[I]) -> Json {
    serde_json::to_value(seq).expect("input serialization cannot fail for corpus use")
}

/// Run a fuzz campaign.
///
/// For `cycles` iterations a fresh `Rng` (seeded `base_seed + cycle`)
/// produces a candidate sequence via `generate`; `check` runs it. On
/// failure the sequence is shrunk while `check` still fails, recorded with
/// its seed, and optionally appended to the failure store under
/// `corpus_dir/failures/`.
pub fn fuzz<I, G, F>(
    base_seed: u64,
    cycles: usize,
    generate: G,
    mut check: F,
    failure_dir: Option<&Path>,
) -> FuzzReport<I>
where
    I: Serialize + Clone,
    G: Fn(&mut Rng, u64) -> Vec<I>,
    F: FnMut(&[I]) -> Result<(), String>,
{
    let mut failures = Vec::new();
    for cycle in 0..cycles {
        let seed = base_seed.wrapping_add(cycle as u64);
        let mut rng = Rng::new(seed);
        let candidate = generate(&mut rng, seed);
        if let Err(reason) = check(&candidate) {
            let (minimal, _) = shrink::shrink(&candidate, |seq| check(seq).is_err());
            let minimal_reason = check(&minimal).err().unwrap_or_else(|| reason.clone());
            failures.push(MinimizedFailure {
                seed,
                reason: minimal_reason,
                input: minimal,
            });
        }
    }
    if let Some(dir) = failure_dir {
        for failure in &failures {
            store_failure(dir, failure);
        }
    }
    FuzzReport { cycles, failures }
}

/// State-transition-aware campaign: generate legal sequences over `model`
/// and check them.
pub fn fuzz_stateful<M, F>(
    model: &M,
    alphabet: &[M::Input],
    base_seed: u64,
    cycles: usize,
    seq_len: usize,
    check: F,
    failure_dir: Option<&Path>,
) -> FuzzReport<M::Input>
where
    M: AbstractModel,
    M::State: Clone + Ord,
    M::Input: Clone + Ord + Serialize,
    F: FnMut(&[M::Input]) -> Result<(), String>,
{
    fuzz(
        base_seed,
        cycles,
        |rng, _seed| stateful_sequence(model, alphabet, rng, seq_len),
        check,
        failure_dir,
    )
}

/// Re-run a stored failure to confirm it still reproduces.
pub fn replay_failure<I: Clone, F>(
    failure: &MinimizedFailure<I>,
    mut check: F,
) -> Result<(), String>
where
    F: FnMut(&[I]) -> Result<(), String>,
{
    check(&failure.input)
}

fn store_failure<I: Serialize>(dir: &Path, failure: &MinimizedFailure<I>) {
    let failures_dir = dir.join("failures");
    if std::fs::create_dir_all(&failures_dir).is_err() {
        return;
    }
    let payload = serde_json::json!({
        "seed": failure.seed,
        "reason": failure.reason,
        "input": failure.input,
    });
    let name = format!("{}.json", input_digest(&payload));
    let _ = std::fs::write(failures_dir.join(name), payload.to_string());
}

#[cfg(test)]
mod tests {
    use super::*;
    use tpt_concord_property::rng::Rng;

    /// Property under test: no sequence of pushes/pops may over-pop an empty
    /// stack — models the classic "invariant checked during execution".
    fn overpop_check(seq: &[i64]) -> Result<(), String> {
        let mut depth: i64 = 0;
        for &op in seq {
            if op >= 0 {
                depth += 1;
            } else {
                depth -= 1;
                if depth < 0 {
                    return Err(format!("stack underflow at op {op}"));
                }
            }
        }
        Ok(())
    }

    fn gen_ops(rng: &mut Rng, _seed: u64) -> Vec<i64> {
        (0..12)
            .map(|_| if rng.next_u64() % 2 == 0 { 1 } else { -1 })
            .collect()
    }

    #[test]
    fn clean_campaign_reports_no_failures() {
        // Only pushes: can never underflow.
        let report = fuzz(1, 100, |_rng, _s| vec![1i64; 5], overpop_check, None);
        assert!(report.is_clean());
        assert_eq!(report.cycles, 100);
    }

    #[test]
    fn finds_shrinks_and_reproduces_failure() {
        let report = fuzz(7, 50, gen_ops, overpop_check, None);
        assert!(
            !report.is_clean(),
            "random push/pop must eventually underflow"
        );
        let failure = &report.failures[0];
        // Minimal failing sequence for underflow is a single pop.
        assert_eq!(failure.input, vec![-1]);
        // Reproducible: replaying the stored failure fails identically.
        assert!(replay_failure(failure, overpop_check).is_err());
        // The seed regenerates the original failing candidate.
        let original = gen_ops(&mut Rng::new(failure.seed), failure.seed);
        assert!(overpop_check(&original).is_err());
    }

    #[test]
    fn failures_are_persisted_and_deduped() {
        let tmp = std::env::temp_dir().join(format!("concord-fuzz-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let report = fuzz(3, 30, gen_ops, overpop_check, Some(&tmp));
        assert!(!report.is_clean());
        let stored: Vec<_> = std::fs::read_dir(tmp.join("failures")).unwrap().collect();
        assert!(!stored.is_empty());
        // Same campaign again → same failure content → same file names.
        fuzz(3, 30, gen_ops, overpop_check, Some(&tmp));
        let stored_again: Vec<_> = std::fs::read_dir(tmp.join("failures")).unwrap().collect();
        assert_eq!(
            stored.len(),
            stored_again.len(),
            "failures dedupe by content"
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
